---
aliases:
  - &test
      working_directory: ~/cli
      steps:
        - checkout
        - restore-cache: &restore_cache
            keys:
              - v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
              - v1-yarn-{{checksum ".circleci/config.yml"}}
        - run: &yarn_install
            command: yarn install
        - run: yarn test
version: 2
jobs:
  node-latest:
    <<: *test
    docker:
      - image: node:latest
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore-cache: *restore_cache
      - run: *yarn-install
      - run: yarn add -D nyc@13 @oclif/nyc-config@1
      - run: $NYC yarn test
      - run: |
          $NYC report --reporter text-lcov > coverage.lcov
          curl -s https://codecov.io/bash | bash
  node-12:
    <<: *test
    docker:
      - image: node:12
  node-10:
    <<: *test
    docker:
      - image: node:10
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: yarn global add @oclif/semantic-release@3 semantic-release@15
      - run: yarn --frozen-lockfile
      - run: |
          export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
          semantic-release -e @oclif/semantic-release
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@oclif/errors":
    jobs:
      - node-latest
      - node-12
      - node-10
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-12
            - node-10
